# Home
curl http://myesp.local

# Scan
curl http://myesp.local/scan

# Connect
curl -X POST http://myesp.local/wifi/connect -d "ssid=home_wifi&pass=home_wifi_123"

# Status
curl http://myesp.local/wifi/status

/wifi/update_ap_password

# Config
# curl -X POST http://myesp.local/config -H "Content-Type: application/json" -d '{
#   "devices": [
#     {
#       "components": [
#         {
#           "componentName": "sensor_led_touch_1",
#           "componentType": "digital",
#           "componentPin": 4,
#           "actionType": "digital",
#           "actionPin": 5,
#           "behaviors": ["toggle"],
#           "schedule": {
#             "startTime": {
#               "hour": 8,
#               "minute": 30
#             },
#             "endTime": {
#               "hour": 17,
#               "minute": 45
#             }
#           }
#         }
#       ]
#     }
#   ]
# }'

# curl -X POST http://myesp.local/config -H "Content-Type: application/json" -d '{
#   "components": [
#     {
#       "name": "ToggleComponent",
#       "inputPins": [5],
#       "outputPins": [4],
#       "conditions": [
#         "if readDigital D2 = on check_previous then toggle pin D1"
#       ]
#     }
#   ]
# }'

curl -X PUT -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode 'config={
  "version": "0.1",
  "pins": [
    {
      "id": "pin1",
      "label": "D1",
      "type": "digital",
      "gpio": 5,
      "mode": "OUTPUT"
    },
    {
      "id": "pin2",
      "label": "D2",
      "type": "digital",
      "gpio": 4,
      "mode": "INPUT"
    }
  ],
  "devices": [
    {
      "id": "led",
      "label": "LED",
      "pins": ["pin1"],
      "state": {
        "status": true
      },
      "latency": 0
    },
    {
      "id": "touch_sensor",
      "label": "Touch Sensor",
      "pins": ["pin2"],
      "state": {
        "touched": false
      },
      "latency": 0
    }
  ],
  "components": [
    {
      "id": "led_switch_deviceComponent",
      "device_id": "led",
      "property": "status",
      "type": "switch"
    }
  ],
  "rules": [
    {
      "id": "rule3",
      "label": "Touch Sensor to Toggle LED",
      "triggerOnChange": true,
      "conditions": [
        {
          "device_id": "touch_sensor",
          "property": "touched",
          "operator": "==",
          "value": true
        }
      ],
      "actions": [
        {
          "device_id": "led",
          "property": "status",
          "action_type": "toggle",
          "value": true
        }
      ]
    }
  ],
}' "http://myesp.local/config/update"


# Control
curl -X POST http://myesp.local/state/set -d 'deviceComponentId=led_switch_deviceComponent&newState=true'

